export default function ExportButton({ plan }) {
  const handleExportPDF = () => {
    if (!plan) {
      alert("No plan to export");
      return;
    }

    // Create HTML content for PDF
    const htmlContent = `
<!DOCTYPE html>
<html>
<head>
  <meta charset="UTF-8">
  <title>Study Plan</title>
  <style>
    body {
      font-family: Arial, sans-serif;
      margin: 20px;
      color: #333;
    }
    h1 {
      color: #2563eb;
      border-bottom: 3px solid #2563eb;
      padding-bottom: 10px;
    }
    h2 {
      color: #1e40af;
      margin-top: 25px;
      border-bottom: 2px solid #ddd;
      padding-bottom: 5px;
    }
    h3 {
      color: #374151;
      margin-top: 20px;
    }
    table {
      width: 100%;
      border-collapse: collapse;
      margin: 15px 0;
      box-shadow: 0 2px 4px rgba(0,0,0,0.1);
    }
    th {
      background-color: #2563eb;
      color: white;
      padding: 12px;
      text-align: left;
      font-weight: 600;
    }
    td {
      padding: 10px 12px;
      border-bottom: 1px solid #e5e7eb;
    }
    tr:nth-child(even) {
      background-color: #f9fafb;
    }
    tr:hover {
      background-color: #f3f4f6;
    }
    .summary-box {
      background-color: #eff6ff;
      border-left: 4px solid #2563eb;
      padding: 15px;
      margin: 15px 0;
      border-radius: 4px;
    }
    .summary-box p {
      margin: 5px 0;
    }
    .warning-box {
      background-color: #fef3c7;
      border-left: 4px solid #f59e0b;
      padding: 15px;
      margin: 15px 0;
      border-radius: 4px;
    }
    .badge {
      display: inline-block;
      padding: 4px 8px;
      border-radius: 4px;
      font-size: 12px;
      font-weight: 600;
    }
    .badge-learning {
      background-color: #dbeafe;
      color: #1e40af;
    }
    .badge-revision {
      background-color: #ede9fe;
      color: #6b21a8;
    }
    .footer {
      margin-top: 30px;
      text-align: center;
      color: #6b7280;
      font-size: 12px;
      border-top: 1px solid #e5e7eb;
      padding-top: 15px;
    }
  </style>
</head>
<body>
  <h1>📚 Study Plan</h1>
  
  <div class="summary-box">
    <h3>📊 Plan Summary</h3>
    <p><strong>Generated:</strong> ${new Date(
      plan.meta.generatedAt
    ).toLocaleDateString()}</p>
    <p><strong>Duration:</strong> ${plan.meta.durationDays} days (${
      plan.meta.learningDays
    } learning days + ${plan.meta.revisionDays} revision day)</p>
    <p><strong>Total Available Hours:</strong> ${
      plan.meta.totalAvailableHours
    }h</p>
    <p><strong>Learning Hours:</strong> ${plan.meta.allocatedLearningHours}h</p>
    <p><strong>Revision Hours:</strong> ${plan.meta.allocatedRevisionHours}h</p>
    <p><strong>Coverage:</strong> ${plan.meta.coveragePercent}%</p>
  </div>

  ${
    plan.warnings && plan.warnings.length > 0
      ? `
  <div class="warning-box">
    <h3>⚠️ Warnings</h3>
    ${plan.warnings.map((w) => `<p>• ${w}</p>`).join("")}
  </div>
  `
      : ""
  }

  <h2>📖 Topics Overview</h2>
  <table>
    <thead>
      <tr>
        <th>Topic</th>
        <th>Difficulty</th>
        <th>Total Hours</th>
        <th>Allocated Hours</th>
        <th>Progress</th>
      </tr>
    </thead>
    <tbody>
      ${plan.topicsSummary
        .map(
          (topic) => `
        <tr>
          <td>${topic.name}</td>
          <td>${"⭐".repeat(topic.difficulty)}</td>
          <td>${topic.totalHours}h</td>
          <td>${topic.allocatedHours}h</td>
          <td>${topic.progress}%</td>
        </tr>
      `
        )
        .join("")}
    </tbody>
  </table>

  <h2>📅 Daily Schedule</h2>
  ${plan.dailyPlan
    .map(
      (day) => `
    <h3>Day ${day.day} - ${day.availabilityHours}h available</h3>
    <table>
      <thead>
        <tr>
          <th>Duration</th>
          <th>Topic</th>
          <th>Subtopic</th>
          <th>Type</th>
        </tr>
      </thead>
      <tbody>
        ${day.sessions
          .map(
            (session) => `
          <tr>
            <td>${session.duration}h</td>
            <td>${session.topic}</td>
            <td>${session.subtopic || "-"}</td>
            <td><span class="badge badge-${
              session.type === "revision" ? "revision" : "learning"
            }">${
              session.type === "revision" ? "🔄 Revision" : "📖 Learning"
            }</span></td>
          </tr>
        `
          )
          .join("")}
      </tbody>
    </table>
  `
    )
    .join("")}

  <div class="footer">
    <p>Generated by Aura Planner on ${new Date().toLocaleDateString()}</p>
  </div>
</body>
</html>
    `;

    // Create a new window for printing
    const printWindow = window.open("", "_blank");
    printWindow.document.write(htmlContent);
    printWindow.document.close();

    // Wait for content to load, then trigger print dialog
    printWindow.onload = () => {
      printWindow.print();
    };
  };

  return (
    <button
      onClick={handleExportPDF}
      disabled={!plan}
      className={`px-6 py-2 rounded-lg transition-all duration-200 shadow-md ${
        plan
          ? "bg-green-500 text-white hover:bg-green-600 hover:shadow-lg hover:scale-105 active:scale-100"
          : "bg-gray-300 text-gray-500 cursor-not-allowed"
      }`}
    >
      📄 Export PDF
    </button>
  );
}
